* typing-categories
When debugging code, it is not unusual to insert temporary print commands to find the bug. After finding it though and correcting it, one may need to keep those print statements to find an additional bug. So just undoing all those changes and changing the bugged code isn't enough because you have to reinsert the code used for debugging. So reverting the file with a version control system or using undo is not the best option in those kinds of situations. This package defines a typing category for inserted text. All text inserted belongs to typing-category 0 by default (this can be change through altering the value of 'typing-category-default' variable. It is possible to instruct the package to change the typing-category to a single digit number (0-9). Everything inserted from that moment and after will belong to this typing-category. Finally a category can be deleted leaving only the characters belonging to all the other active categories.

** Installation

This package is available through MELPA.

It can be set up using use-package:

#+BEGIN_SRC emacs-lisp
(use-package typing-categories
		:bind (
		 ("C-x t t" . typing-category)
		 ("C-x t c" . change-typing-category)
		 ("C-x t d" . delete-typing-category)
		 ("C-x t r" . reset-typing-category)
		 ("C-x t p" . current-typing-category)
		 )
		)
#+END_SRC
