* typing-categories
When debugging code, it is not unusual to insert print statements and other temporary code in the program to locate the bugs. After locating all of them, it is impossible to undo or revert just the code used for debugging because it will revert the bug corrections too. This package defines a typing category for inserted text. All text inserted belongs to typing-category 0 by default (this can be change through altering the value of 'typing-category-default' variable). It is possible to instruct the package to change the typing-category to a single digit number (0-9). Everything inserted from that moment and after will belong to the new typing-category. Finally a category can be deleted leaving only the characters belonging to all the other active categories.

** Installation

This package is available through MELPA.

It can be set up using use-package:

#+BEGIN_SRC emacs-lisp
(use-package typing-categories
		:bind (
		 ("C-x t t" . typing-category)
		 ("C-x t c" . change-typing-category)
		 ("C-x t d" . delete-typing-category)
		 ("C-x t r" . reset-typing-category)
		 ("C-x t p" . current-typing-category)
		 )
		)
#+END_SRC
